name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*
      - dev
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - run: npm ci
      - run: npm run build
      - run: npm test
